// Auto-generated by `npm run cms:pull`.
// Committed snapshot — mirrors the latest Sanity content.
// Do not edit manually. Re-run `npm run cms:pull` after CMS changes.

export const syncedContentMeta = {
  "syncedAt": "2026-07-24T20:55:19.995Z",
  "source": "sanity",
  "projectId": "nzfscoez",
  "dataset": "production",
  "categoriesCount": 6,
  "productsCount": 28
};

export const syncedSiteSettings = {
  "aboutBrandsDescription": "Our furniture features premium wooden frames and cane frames, crafted to ensure durability for residential, corporate, and commercial use.",
  "aboutBrandsEyebrow": "Materials & Quality",
  "aboutBrandsTitle": "Built with the best Wood, Steel, and Frame Materials.",
  "aboutHeroEyebrow": "About Unique Sofa World",
  "aboutHeroSubtitle": "We specialize in custom furniture, sofa manufacturing, bed manufacturing, and expert repair services across Bengaluru.",
  "aboutHeroTitle": "Your Trusted Custom Furniture Manufacturer & Dealer.",
  "aboutModelDescription": "We don't just sell furniture. We are a custom furniture manufacturer, a reliable office furniture supplier, and specialists in sofa repair and restoration.",
  "aboutModelEyebrow": "Our core services",
  "aboutModelTitle": "Manufacturing, Supply, and Restoration.",
  "aboutPrimaryCtaLabel": "View our work",
  "aboutSecondaryCtaLabel": "Contact us",
  "brandLogoUrl": null,
  "brandName": "Unique Sofa World Furniture",
  "brandShortName": "Unique Sofa World",
  "brandSupportLabel": "Crafting Comfortable Living Spaces",
  "brands": [
    "Unique Sofa World",
    "Custom Craft",
    "Premium Wood",
    "Steel Masters",
    "Luxury Comfort"
  ],
  "city": "Bengaluru, India",
  "contactBusinessHoursSunday": "Daily: 10:00 AM – 9:00 PM",
  "contactBusinessHoursWeekday": "Daily: 10:00 AM – 9:00 PM",
  "contactEnquiryDescription": "Tell us about your home or commercial furniture requirements, or share pictures of the sofa you need repaired.",
  "contactEnquiryEyebrow": "Send an enquiry",
  "contactEnquirySentDescription": "If WhatsApp didn't launch, please message us directly.",
  "contactEnquirySentTitle": "WhatsApp ready",
  "contactEnquirySubmitLabel": "Send via WhatsApp",
  "contactEnquiryTitle": "Discuss your project",
  "contactHeroEyebrow": "Contact Us",
  "contactHeroSubtitle": "Reach out to Unique Sofa World for your furniture needs. We offer a shop-in-store experience and reliable delivery services.",
  "contactHeroTitle": "Get in touch for custom orders, repairs, or a quick visit.",
  "contactQuickContactEyebrow": "Quick connect",
  "contactWhatsappDescription": "Fast replies for custom quotes, repair queries, and site visits.",
  "contactWhatsappTitle": "WhatsApp us",
  "email": "uniquesofaworldfurniture@gmail.com",
  "emailHref": "mailto:uniquesofaworldfurniture@gmail.com",
  "featuredCategoryIds": [
    {
      "id": "sofas"
    },
    {
      "id": "beds"
    },
    {
      "id": "recliners"
    },
    {
      "id": "chairs"
    },
    {
      "id": "dining-tables"
    },
    {
      "id": "center-tables"
    }
  ],
  "featuredProductIds": [
    {
      "id": "sofas-3-seater"
    },
    {
      "id": "sofas-l-shape"
    },
    {
      "id": "sofas-luxury"
    },
    {
      "id": "beds-king-size"
    },
    {
      "id": "beds-upholstered"
    },
    {
      "id": "recliners-premium"
    },
    {
      "id": "chairs-lounge-chairs"
    },
    {
      "id": "dining-tables-6-seater"
    }
  ],
  "footerBottomCaption": "Unique Sofa World Furniture | Custom Sofas, Beds & Repair Services.",
  "footerContactTitle": "Get in Touch",
  "footerNavigateTitle": "Navigate",
  "footerStoresTitle": "Visit Us",
  "headerCtaLabel": "Request a Visit",
  "heroFloatingCardImage": "https://cdn.sanity.io/images/nzfscoez/production/d198e222a42ecce6ac3754193f8c7af292b45422-1024x1024.jpg",
  "heroFloatingCardTitle": "Custom Sofas",
  "heroHappyCustomersCount": "5K+",
  "heroHappyCustomersLabel": "Happy Customers",
  "heroMedia": [
    {
      "description": "Discover our premium selection of modern seating designed for unparalleled comfort and style.",
      "eyebrow": "New Collection",
      "image": "https://cdn.sanity.io/images/nzfscoez/production/7dee833edc893611403543272e98b9c5b75e64cd-1024x1536.png",
      "title": "Modern"
    },
    {
      "description": "Handcrafted sofas built to elevate your living spaces with premium fabrics and timeless design.",
      "eyebrow": "Luxury Living",
      "image": "https://cdn.sanity.io/images/nzfscoez/production/45ba52b9777dc9d323746e136fcaa7d40eb27072-1024x504.png",
      "title": "Comfort"
    },
    {
      "description": "Elegant bed frames crafted for restful spaces - where quality meets lasting style.",
      "eyebrow": "Premium Beds",
      "image": "https://cdn.sanity.io/images/nzfscoez/production/0535738aa1e3829d20ec8641b4bfcf1d24e5900d-1024x619.png",
      "title": "Serene"
    }
  ],
  "homeBrandsDescription": "We provide furniture solutions for Residential Homes, Hotels, Restaurants, Offices, Hospitals, and Industrial Facilities with guaranteed service and delivery.",
  "homeBrandsEyebrow": "Our Clients & Reach",
  "homeBrandsTitle": "Serving homes, offices, and commercial spaces.",
  "homeFeaturedProductsDescription": "View our custom manufactured pieces and learn about our dedicated sofa and furniture repair services.",
  "homeFeaturedProductsEyebrow": "Our specialties",
  "homeFeaturedProductsTitle": "Premium products and expert repair.",
  "homeFeaturedRangesDescription": "From residential homes to hotels and corporate spaces, explore our carefully categorized furniture solutions.",
  "homeFeaturedRangesEyebrow": "Furniture categories",
  "homeFeaturedRangesTitle": "Designed for every space in your life.",
  "homeWhyDescription": "As a premier furniture dealer and custom manufacturer, we offer exceptional sofa manufacturing, bed manufacturing, and comprehensive repair & restoration services.",
  "homeWhyEyebrow": "Why Unique Sofa World",
  "homeWhyTitle": "Custom built. Expertly repaired. Beautifully designed.",
  "intro": "Unique Sofa World Furniture is a trusted custom furniture manufacturer and dealer in Bengaluru. We specialize in premium sofas, beds, dining tables, modular furniture, and offer expert sofa repair and upholstery services for residential, commercial, and industrial spaces.",
  "navItems": [
    {
      "href": "/",
      "label": "Home"
    },
    {
      "href": "/products",
      "label": "Products"
    },
    {
      "href": "/about",
      "label": "About"
    },
    {
      "href": "/contact",
      "label": "Contact"
    }
  ],
  "phoneDisplay": "+91 95911 67804",
  "phoneHref": "tel:+919591167804",
  "phoneRaw": "919591167804",
  "productsFilterBrandLabel": "Brand",
  "productsFilterFamilyLabel": "Category",
  "productsFilterRangeLabel": "Style",
  "productsHeroEyebrow": "Furniture collection",
  "productsHeroSubtitle": "Discover sofas, beds, dining sets, modular units, and designer pieces crafted to perfection.",
  "productsHeroTitle": "Browse our extensive furniture range.",
  "productsNoResultDescription": "Try adjusting the family, range, or brand filter to find what you need.",
  "productsNoResultEyebrow": "No results",
  "productsNoResultResetLabel": "Clear filters",
  "productsNoResultTitle": "No products match your filters.",
  "productsSummaryDescription": "Browse all Unique Sofa World products, from luxury designer pieces to sturdy office setups and custom outdoor furniture.",
  "productsSummaryTitle": "Filter by category and style.",
  "specializations": [
    {
      "items": [
        "Custom Sofas & Sofa Sets",
        "Bed Manufacturing",
        "Wooden & Steel Furniture",
        "Modular Furniture"
      ],
      "summary": "Bespoke furniture crafted to your exact specifications. We build sofas, beds, dining tables, and office furniture tailored to your space.",
      "title": "Custom Furniture Manufacturing"
    },
    {
      "items": [
        "Sofa & Sofa Set Repair",
        "Fabric & Leather Re-upholstery",
        "Frame Structural Repair",
        "Cushion Refill"
      ],
      "summary": "Expert repair and re-upholstery services to bring your worn-out sofas and furniture back to life with premium materials.",
      "title": "Sofa Repair & Restoration"
    },
    {
      "items": [
        "Living & Bedroom Furniture",
        "Office & Corporate Desks",
        "Outdoor Furniture Solutions",
        "Hotel & Restaurant Seating"
      ],
      "summary": "Providing complete furniture solutions for homes, hotels, restaurants, offices, hospitals, and corporate spaces.",
      "title": "Residential & Commercial Furniture"
    }
  ],
  "stats": [
    {
      "label": "Established",
      "value": "2021"
    },
    {
      "label": "Products & Projects",
      "value": "500+"
    },
    {
      "label": "Store location",
      "value": "1"
    },
    {
      "label": "Happy customers",
      "value": "5K+"
    }
  ],
  "stores": [
    {
      "address": "Sri Sai Himaja Apartment, 307/2, Nyanappana Halli Main Rd, 11th Cross Rd, Devarachikkana Halli",
      "city": "Bengaluru 560114",
      "mapsUrl": "https://maps.app.goo.gl/Lohwr2jbq6ZcmedM9",
      "name": "Unique Sofa World Furniture",
      "type": "Main Store & Workshop"
    }
  ],
  "whatsappHref": "https://wa.me/919591167804?text=Hello%2C%20I%27m%20interested%20in%20your%20furniture%20and%20sofa%20services.%20Could%20you%20please%20assist%20me%3F"
};

export const syncedCategories = [
  {
    "accent": "#bf622c",
    "badge": "Best Seller",
    "code": "SF",
    "family": "sofas",
    "id": "sofas",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/09ac0cb53238317c7fd4c23689d640926e81253a-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/9b45504ed6be5a4c9ded0b23013d66b9cd9ee259-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/e9c55a98444fce6fbf958efd4cec3ede443b439b-992x1403.jpg"
    ],
    "items": [
      "Sofa",
      "Living Room",
      "Upholstered",
      "Custom"
    ],
    "slug": "sofas",
    "subtitle": "Comfortable seating for every home",
    "summary": "Premium handcrafted sofas in modern, luxury, sectional, and custom designs.",
    "title": "Sofas",
    "tone": "#f9ece3"
  },
  {
    "accent": "#2563eb",
    "badge": "Popular",
    "code": "BD",
    "family": "beds",
    "id": "beds",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/c6340cc6b8de139ccb0f6089cbdc923b64e7cc6d-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/e972f300de6cd29fb1fa7167d73434c757819a96-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/7b53249213ed8cc94d4f92c345b6472a6be45f73-992x1403.jpg"
    ],
    "items": [
      "Bed",
      "Bedroom",
      "King Size",
      "Queen Size"
    ],
    "slug": "beds",
    "subtitle": "Crafted for comfort and style",
    "summary": "Custom wooden and upholstered beds designed for durability and elegant bedrooms.",
    "title": "Beds",
    "tone": "#e9f1ff"
  },
  {
    "accent": "#7c3aed",
    "badge": "Premium",
    "code": "RC",
    "family": "recliners",
    "id": "recliners",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/64016a12d4a271de2b307c3a2f269c862e32c197-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/cfc70dda8cde55f478fd7c1ea5f13e621bd5772a-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/98201f82bca7ac27b5f1a2f06dd0f11081891650-992x1403.jpg"
    ],
    "items": [
      "Recliner",
      "Lounge",
      "Comfort"
    ],
    "slug": "recliners",
    "subtitle": "Relax in premium comfort",
    "summary": "Manual and premium recliners with ergonomic support and luxurious cushioning.",
    "title": "Recliners",
    "tone": "#f1eaff"
  },
  {
    "accent": "#1f8f56",
    "badge": "",
    "code": "CH",
    "family": "chairs",
    "id": "chairs",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/463ba6bd604f3e715783d0431dcd1f727ebff83f-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/7ba3b8f08be22894cde5c61159442b78759413a2-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/ff00a0dbd609987bbb2b9b31be073c9bf414365c-992x1403.jpg"
    ],
    "items": [
      "Chair",
      "Wooden Chair",
      "Accent Chair"
    ],
    "slug": "chairs",
    "subtitle": "Stylish seating solutions",
    "summary": "Wooden, accent, dining, and sofa chairs handcrafted for homes and offices.",
    "title": "Chairs",
    "tone": "#eaf7ef"
  },
  {
    "accent": "#d62e63",
    "badge": "New",
    "code": "DT",
    "family": "dining",
    "id": "dining-tables",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/515fb87adfcfd4c5d41c593e7b9dfaf110a7d4ff-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/8721eb1829ace437740ac3bc6ccda3b8bff0a638-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/b0acd4b39600a872d82f59d8b106191860017331-992x1403.jpg"
    ],
    "items": [
      "Dining",
      "Table",
      "Family Dining"
    ],
    "slug": "dining-tables",
    "subtitle": "Elegant dining experiences",
    "summary": "Modern and classic dining tables available in multiple sizes and finishes.",
    "title": "Dining Tables",
    "tone": "#ffe8f0"
  },
  {
    "accent": "#1186a0",
    "badge": "",
    "code": "CT",
    "family": "tables",
    "id": "center-tables",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/5a31f4f89b4a3bbfe05e2b28e5dd0997123a10ff-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/dcaf41dccf588f3852c809b8d7449bddc4d5fd9b-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/64547298c76ff387763341204614b37deb0d4024-992x1403.jpg"
    ],
    "items": [
      "Center Table",
      "Coffee Table"
    ],
    "slug": "center-tables",
    "subtitle": "Complete your living space",
    "summary": "Contemporary center and coffee tables crafted from premium materials.",
    "title": "Center Tables",
    "tone": "#e7f8fb"
  }
];

export const syncedProducts = [
  {
    "badge": "Best Seller",
    "brand": "Unique Sofa World",
    "categoryId": "sofas",
    "categoryTitle": "Sofas",
    "description": "Our 3-Seater is part of the Sofas collection. Designed for comfortable seating for every home, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "sofas",
    "features": [
      "Handcrafted 3-Seater built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "sofas-3-seater",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/09ac0cb53238317c7fd4c23689d640926e81253a-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/9b45504ed6be5a4c9ded0b23013d66b9cd9ee259-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/e9c55a98444fce6fbf958efd4cec3ede443b439b-992x1403.jpg"
    ],
    "name": "3-Seater",
    "slug": "sofas-3-seater",
    "specs": [
      {
        "label": "Category",
        "value": "Sofas"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "3-Seater"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium 3-Seater by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Sofas",
      "3-Seater",
      "Unique Sofa World"
    ],
    "type": "3-Seater"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "sofas",
    "categoryTitle": "Sofas",
    "description": "Our L-Shape is part of the Sofas collection. Designed for comfortable seating for every home, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "sofas",
    "features": [
      "Handcrafted L-Shape built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "sofas-l-shape",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/9b45504ed6be5a4c9ded0b23013d66b9cd9ee259-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/e9c55a98444fce6fbf958efd4cec3ede443b439b-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/b34a58212e61d849c4a98c8fe152351d98affe3b-992x1403.jpg"
    ],
    "name": "L-Shape",
    "slug": "sofas-l-shape",
    "specs": [
      {
        "label": "Category",
        "value": "Sofas"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "L-Shape"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium L-Shape by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Sofas",
      "L-Shape",
      "Unique Sofa World"
    ],
    "type": "L-Shape"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "sofas",
    "categoryTitle": "Sofas",
    "description": "Our Sectional is part of the Sofas collection. Designed for comfortable seating for every home, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "sofas",
    "features": [
      "Handcrafted Sectional built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "sofas-sectional",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/e9c55a98444fce6fbf958efd4cec3ede443b439b-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/b34a58212e61d849c4a98c8fe152351d98affe3b-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/09ac0cb53238317c7fd4c23689d640926e81253a-992x1403.jpg"
    ],
    "name": "Sectional",
    "slug": "sofas-sectional",
    "specs": [
      {
        "label": "Category",
        "value": "Sofas"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Sectional"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Sectional by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Sofas",
      "Sectional",
      "Unique Sofa World"
    ],
    "type": "Sectional"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "sofas",
    "categoryTitle": "Sofas",
    "description": "Our Chesterfield is part of the Sofas collection. Designed for comfortable seating for every home, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "sofas",
    "features": [
      "Handcrafted Chesterfield built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "sofas-chesterfield",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/b34a58212e61d849c4a98c8fe152351d98affe3b-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/09ac0cb53238317c7fd4c23689d640926e81253a-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/9b45504ed6be5a4c9ded0b23013d66b9cd9ee259-992x1403.jpg"
    ],
    "name": "Chesterfield",
    "slug": "sofas-chesterfield",
    "specs": [
      {
        "label": "Category",
        "value": "Sofas"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Chesterfield"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Chesterfield by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Sofas",
      "Chesterfield",
      "Unique Sofa World"
    ],
    "type": "Chesterfield"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "sofas",
    "categoryTitle": "Sofas",
    "description": "Our Modern is part of the Sofas collection. Designed for comfortable seating for every home, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "sofas",
    "features": [
      "Handcrafted Modern built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "sofas-modern",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/09ac0cb53238317c7fd4c23689d640926e81253a-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/9b45504ed6be5a4c9ded0b23013d66b9cd9ee259-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/e9c55a98444fce6fbf958efd4cec3ede443b439b-992x1403.jpg"
    ],
    "name": "Modern",
    "slug": "sofas-modern",
    "specs": [
      {
        "label": "Category",
        "value": "Sofas"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Modern"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Modern by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Sofas",
      "Modern",
      "Unique Sofa World"
    ],
    "type": "Modern"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "sofas",
    "categoryTitle": "Sofas",
    "description": "Our Luxury is part of the Sofas collection. Designed for comfortable seating for every home, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "sofas",
    "features": [
      "Handcrafted Luxury built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "sofas-luxury",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/9b45504ed6be5a4c9ded0b23013d66b9cd9ee259-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/e9c55a98444fce6fbf958efd4cec3ede443b439b-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/b34a58212e61d849c4a98c8fe152351d98affe3b-992x1403.jpg"
    ],
    "name": "Luxury",
    "slug": "sofas-luxury",
    "specs": [
      {
        "label": "Category",
        "value": "Sofas"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Luxury"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Luxury by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Sofas",
      "Luxury",
      "Unique Sofa World"
    ],
    "type": "Luxury"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "sofas",
    "categoryTitle": "Sofas",
    "description": "Our Wooden is part of the Sofas collection. Designed for comfortable seating for every home, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "sofas",
    "features": [
      "Handcrafted Wooden built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "sofas-wooden",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/e9c55a98444fce6fbf958efd4cec3ede443b439b-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/b34a58212e61d849c4a98c8fe152351d98affe3b-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/09ac0cb53238317c7fd4c23689d640926e81253a-992x1403.jpg"
    ],
    "name": "Wooden",
    "slug": "sofas-wooden",
    "specs": [
      {
        "label": "Category",
        "value": "Sofas"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Wooden"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Wooden by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Sofas",
      "Wooden",
      "Unique Sofa World"
    ],
    "type": "Wooden"
  },
  {
    "badge": "Popular",
    "brand": "Unique Sofa World",
    "categoryId": "beds",
    "categoryTitle": "Beds",
    "description": "Our King Size is part of the Beds collection. Designed for crafted for comfort and style, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "beds",
    "features": [
      "Handcrafted King Size built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "beds-king-size",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/c6340cc6b8de139ccb0f6089cbdc923b64e7cc6d-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/e972f300de6cd29fb1fa7167d73434c757819a96-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/7b53249213ed8cc94d4f92c345b6472a6be45f73-992x1403.jpg"
    ],
    "name": "King Size",
    "slug": "beds-king-size",
    "specs": [
      {
        "label": "Category",
        "value": "Beds"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "King Size"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium King Size by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Beds",
      "King Size",
      "Unique Sofa World"
    ],
    "type": "King Size"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "beds",
    "categoryTitle": "Beds",
    "description": "Our Queen Size is part of the Beds collection. Designed for crafted for comfort and style, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "beds",
    "features": [
      "Handcrafted Queen Size built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "beds-queen-size",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/e972f300de6cd29fb1fa7167d73434c757819a96-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/7b53249213ed8cc94d4f92c345b6472a6be45f73-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/8721eb1829ace437740ac3bc6ccda3b8bff0a638-992x1403.jpg"
    ],
    "name": "Queen Size",
    "slug": "beds-queen-size",
    "specs": [
      {
        "label": "Category",
        "value": "Beds"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Queen Size"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Queen Size by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Beds",
      "Queen Size",
      "Unique Sofa World"
    ],
    "type": "Queen Size"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "beds",
    "categoryTitle": "Beds",
    "description": "Our Storage is part of the Beds collection. Designed for crafted for comfort and style, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "beds",
    "features": [
      "Handcrafted Storage built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "beds-storage",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/7b53249213ed8cc94d4f92c345b6472a6be45f73-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/8721eb1829ace437740ac3bc6ccda3b8bff0a638-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/c6340cc6b8de139ccb0f6089cbdc923b64e7cc6d-992x1403.jpg"
    ],
    "name": "Storage",
    "slug": "beds-storage",
    "specs": [
      {
        "label": "Category",
        "value": "Beds"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Storage"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Storage by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Beds",
      "Storage",
      "Unique Sofa World"
    ],
    "type": "Storage"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "beds",
    "categoryTitle": "Beds",
    "description": "Our Upholstered is part of the Beds collection. Designed for crafted for comfort and style, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "beds",
    "features": [
      "Handcrafted Upholstered built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "beds-upholstered",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/8721eb1829ace437740ac3bc6ccda3b8bff0a638-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/c6340cc6b8de139ccb0f6089cbdc923b64e7cc6d-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/e972f300de6cd29fb1fa7167d73434c757819a96-992x1364.jpg"
    ],
    "name": "Upholstered",
    "slug": "beds-upholstered",
    "specs": [
      {
        "label": "Category",
        "value": "Beds"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Upholstered"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Upholstered by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Beds",
      "Upholstered",
      "Unique Sofa World"
    ],
    "type": "Upholstered"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "beds",
    "categoryTitle": "Beds",
    "description": "Our Wooden is part of the Beds collection. Designed for crafted for comfort and style, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "beds",
    "features": [
      "Handcrafted Wooden built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "beds-wooden",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/c6340cc6b8de139ccb0f6089cbdc923b64e7cc6d-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/e972f300de6cd29fb1fa7167d73434c757819a96-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/7b53249213ed8cc94d4f92c345b6472a6be45f73-992x1403.jpg"
    ],
    "name": "Wooden",
    "slug": "beds-wooden",
    "specs": [
      {
        "label": "Category",
        "value": "Beds"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Wooden"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Wooden by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Beds",
      "Wooden",
      "Unique Sofa World"
    ],
    "type": "Wooden"
  },
  {
    "badge": "Premium",
    "brand": "Unique Sofa World",
    "categoryId": "recliners",
    "categoryTitle": "Recliners",
    "description": "Our Manual is part of the Recliners collection. Designed for relax in premium comfort, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "recliners",
    "features": [
      "Handcrafted Manual built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "recliners-manual",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/64016a12d4a271de2b307c3a2f269c862e32c197-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/cfc70dda8cde55f478fd7c1ea5f13e621bd5772a-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/98201f82bca7ac27b5f1a2f06dd0f11081891650-992x1403.jpg"
    ],
    "name": "Manual",
    "slug": "recliners-manual",
    "specs": [
      {
        "label": "Category",
        "value": "Recliners"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "In Stock & Custom"
      },
      {
        "label": "Style",
        "value": "Manual"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium Manual by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Recliners",
      "Manual",
      "Unique Sofa World"
    ],
    "type": "Manual"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "recliners",
    "categoryTitle": "Recliners",
    "description": "Our Rocker is part of the Recliners collection. Designed for relax in premium comfort, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "recliners",
    "features": [
      "Handcrafted Rocker built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "recliners-rocker",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/cfc70dda8cde55f478fd7c1ea5f13e621bd5772a-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/98201f82bca7ac27b5f1a2f06dd0f11081891650-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/463ba6bd604f3e715783d0431dcd1f727ebff83f-992x1403.jpg"
    ],
    "name": "Rocker",
    "slug": "recliners-rocker",
    "specs": [
      {
        "label": "Category",
        "value": "Recliners"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "In Stock & Custom"
      },
      {
        "label": "Style",
        "value": "Rocker"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium Rocker by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Recliners",
      "Rocker",
      "Unique Sofa World"
    ],
    "type": "Rocker"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "recliners",
    "categoryTitle": "Recliners",
    "description": "Our Swivel is part of the Recliners collection. Designed for relax in premium comfort, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "recliners",
    "features": [
      "Handcrafted Swivel built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "recliners-swivel",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/98201f82bca7ac27b5f1a2f06dd0f11081891650-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/463ba6bd604f3e715783d0431dcd1f727ebff83f-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/64016a12d4a271de2b307c3a2f269c862e32c197-992x1403.jpg"
    ],
    "name": "Swivel",
    "slug": "recliners-swivel",
    "specs": [
      {
        "label": "Category",
        "value": "Recliners"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "In Stock & Custom"
      },
      {
        "label": "Style",
        "value": "Swivel"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium Swivel by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Recliners",
      "Swivel",
      "Unique Sofa World"
    ],
    "type": "Swivel"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "recliners",
    "categoryTitle": "Recliners",
    "description": "Our Premium is part of the Recliners collection. Designed for relax in premium comfort, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "recliners",
    "features": [
      "Handcrafted Premium built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "recliners-premium",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/463ba6bd604f3e715783d0431dcd1f727ebff83f-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/64016a12d4a271de2b307c3a2f269c862e32c197-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/cfc70dda8cde55f478fd7c1ea5f13e621bd5772a-992x1364.jpg"
    ],
    "name": "Premium",
    "slug": "recliners-premium",
    "specs": [
      {
        "label": "Category",
        "value": "Recliners"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "In Stock & Custom"
      },
      {
        "label": "Style",
        "value": "Premium"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium Premium by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Recliners",
      "Premium",
      "Unique Sofa World"
    ],
    "type": "Premium"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "chairs",
    "categoryTitle": "Chairs",
    "description": "Our Sofa Chairs is part of the Chairs collection. Designed for stylish seating solutions, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "chairs",
    "features": [
      "Handcrafted Sofa Chairs built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "chairs-sofa-chairs",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/463ba6bd604f3e715783d0431dcd1f727ebff83f-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/7ba3b8f08be22894cde5c61159442b78759413a2-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/ff00a0dbd609987bbb2b9b31be073c9bf414365c-992x1403.jpg"
    ],
    "name": "Sofa Chairs",
    "slug": "chairs-sofa-chairs",
    "specs": [
      {
        "label": "Category",
        "value": "Chairs"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Sofa Chairs"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Sofa Chairs by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Chairs",
      "Sofa Chairs",
      "Unique Sofa World"
    ],
    "type": "Sofa Chairs"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "chairs",
    "categoryTitle": "Chairs",
    "description": "Our Wooden Chairs is part of the Chairs collection. Designed for stylish seating solutions, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "chairs",
    "features": [
      "Handcrafted Wooden Chairs built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "chairs-wooden-chairs",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/7ba3b8f08be22894cde5c61159442b78759413a2-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/ff00a0dbd609987bbb2b9b31be073c9bf414365c-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/98201f82bca7ac27b5f1a2f06dd0f11081891650-992x1403.jpg"
    ],
    "name": "Wooden Chairs",
    "slug": "chairs-wooden-chairs",
    "specs": [
      {
        "label": "Category",
        "value": "Chairs"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Wooden Chairs"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Wooden Chairs by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Chairs",
      "Wooden Chairs",
      "Unique Sofa World"
    ],
    "type": "Wooden Chairs"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "chairs",
    "categoryTitle": "Chairs",
    "description": "Our Accent Chairs is part of the Chairs collection. Designed for stylish seating solutions, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "chairs",
    "features": [
      "Handcrafted Accent Chairs built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "chairs-accent-chairs",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/ff00a0dbd609987bbb2b9b31be073c9bf414365c-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/98201f82bca7ac27b5f1a2f06dd0f11081891650-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/463ba6bd604f3e715783d0431dcd1f727ebff83f-992x1403.jpg"
    ],
    "name": "Accent Chairs",
    "slug": "chairs-accent-chairs",
    "specs": [
      {
        "label": "Category",
        "value": "Chairs"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Accent Chairs"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Accent Chairs by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Chairs",
      "Accent Chairs",
      "Unique Sofa World"
    ],
    "type": "Accent Chairs"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "chairs",
    "categoryTitle": "Chairs",
    "description": "Our Lounge Chairs is part of the Chairs collection. Designed for stylish seating solutions, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "chairs",
    "features": [
      "Handcrafted Lounge Chairs built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "chairs-lounge-chairs",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/98201f82bca7ac27b5f1a2f06dd0f11081891650-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/463ba6bd604f3e715783d0431dcd1f727ebff83f-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/7ba3b8f08be22894cde5c61159442b78759413a2-992x1364.jpg"
    ],
    "name": "Lounge Chairs",
    "slug": "chairs-lounge-chairs",
    "specs": [
      {
        "label": "Category",
        "value": "Chairs"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Lounge Chairs"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup, Repair"
      }
    ],
    "summary": "Premium Lounge Chairs by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Chairs",
      "Lounge Chairs",
      "Unique Sofa World"
    ],
    "type": "Lounge Chairs"
  },
  {
    "badge": "New",
    "brand": "Unique Sofa World",
    "categoryId": "dining-tables",
    "categoryTitle": "Dining Tables",
    "description": "Our 4-Seater is part of the Dining Tables collection. Designed for elegant dining experiences, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "dining",
    "features": [
      "Handcrafted 4-Seater built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "dining-tables-4-seater",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/515fb87adfcfd4c5d41c593e7b9dfaf110a7d4ff-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/8721eb1829ace437740ac3bc6ccda3b8bff0a638-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/b0acd4b39600a872d82f59d8b106191860017331-992x1403.jpg"
    ],
    "name": "4-Seater",
    "slug": "dining-tables-4-seater",
    "specs": [
      {
        "label": "Category",
        "value": "Dining Tables"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "4-Seater"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium 4-Seater by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Dining Tables",
      "4-Seater",
      "Unique Sofa World"
    ],
    "type": "4-Seater"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "dining-tables",
    "categoryTitle": "Dining Tables",
    "description": "Our 6-Seater is part of the Dining Tables collection. Designed for elegant dining experiences, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "dining",
    "features": [
      "Handcrafted 6-Seater built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "dining-tables-6-seater",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/8721eb1829ace437740ac3bc6ccda3b8bff0a638-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/b0acd4b39600a872d82f59d8b106191860017331-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/cfc70dda8cde55f478fd7c1ea5f13e621bd5772a-992x1364.jpg"
    ],
    "name": "6-Seater",
    "slug": "dining-tables-6-seater",
    "specs": [
      {
        "label": "Category",
        "value": "Dining Tables"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "6-Seater"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium 6-Seater by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Dining Tables",
      "6-Seater",
      "Unique Sofa World"
    ],
    "type": "6-Seater"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "dining-tables",
    "categoryTitle": "Dining Tables",
    "description": "Our 8-Seater is part of the Dining Tables collection. Designed for elegant dining experiences, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "dining",
    "features": [
      "Handcrafted 8-Seater built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "dining-tables-8-seater",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/b0acd4b39600a872d82f59d8b106191860017331-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/cfc70dda8cde55f478fd7c1ea5f13e621bd5772a-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/515fb87adfcfd4c5d41c593e7b9dfaf110a7d4ff-992x1403.jpg"
    ],
    "name": "8-Seater",
    "slug": "dining-tables-8-seater",
    "specs": [
      {
        "label": "Category",
        "value": "Dining Tables"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "8-Seater"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium 8-Seater by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Dining Tables",
      "8-Seater",
      "Unique Sofa World"
    ],
    "type": "8-Seater"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "dining-tables",
    "categoryTitle": "Dining Tables",
    "description": "Our Marble Top is part of the Dining Tables collection. Designed for elegant dining experiences, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "dining",
    "features": [
      "Handcrafted Marble Top built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "dining-tables-marble-top",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/cfc70dda8cde55f478fd7c1ea5f13e621bd5772a-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/515fb87adfcfd4c5d41c593e7b9dfaf110a7d4ff-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/8721eb1829ace437740ac3bc6ccda3b8bff0a638-992x1403.jpg"
    ],
    "name": "Marble Top",
    "slug": "dining-tables-marble-top",
    "specs": [
      {
        "label": "Category",
        "value": "Dining Tables"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Marble Top"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium Marble Top by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Dining Tables",
      "Marble Top",
      "Unique Sofa World"
    ],
    "type": "Marble Top"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "center-tables",
    "categoryTitle": "Center Tables",
    "description": "Our Center Tables is part of the Center Tables collection. Designed for complete your living space, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "tables",
    "features": [
      "Handcrafted Center Tables built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "center-tables-center-tables",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/5a31f4f89b4a3bbfe05e2b28e5dd0997123a10ff-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/dcaf41dccf588f3852c809b8d7449bddc4d5fd9b-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/64547298c76ff387763341204614b37deb0d4024-992x1403.jpg"
    ],
    "name": "Center Tables",
    "slug": "center-tables-center-tables",
    "specs": [
      {
        "label": "Category",
        "value": "Center Tables"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Center Tables"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium Center Tables by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Center Tables",
      "Center Tables",
      "Unique Sofa World"
    ],
    "type": "Center Tables"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "center-tables",
    "categoryTitle": "Center Tables",
    "description": "Our Coffee Tables is part of the Center Tables collection. Designed for complete your living space, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "tables",
    "features": [
      "Handcrafted Coffee Tables built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "center-tables-coffee-tables",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/dcaf41dccf588f3852c809b8d7449bddc4d5fd9b-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/64547298c76ff387763341204614b37deb0d4024-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/7ba3b8f08be22894cde5c61159442b78759413a2-992x1364.jpg"
    ],
    "name": "Coffee Tables",
    "slug": "center-tables-coffee-tables",
    "specs": [
      {
        "label": "Category",
        "value": "Center Tables"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Coffee Tables"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium Coffee Tables by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Center Tables",
      "Coffee Tables",
      "Unique Sofa World"
    ],
    "type": "Coffee Tables"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "center-tables",
    "categoryTitle": "Center Tables",
    "description": "Our Side Tables is part of the Center Tables collection. Designed for complete your living space, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "tables",
    "features": [
      "Handcrafted Side Tables built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "center-tables-side-tables",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/64547298c76ff387763341204614b37deb0d4024-992x1403.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/7ba3b8f08be22894cde5c61159442b78759413a2-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/5a31f4f89b4a3bbfe05e2b28e5dd0997123a10ff-992x1364.jpg"
    ],
    "name": "Side Tables",
    "slug": "center-tables-side-tables",
    "specs": [
      {
        "label": "Category",
        "value": "Center Tables"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Side Tables"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium Side Tables by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Center Tables",
      "Side Tables",
      "Unique Sofa World"
    ],
    "type": "Side Tables"
  },
  {
    "badge": "",
    "brand": "Unique Sofa World",
    "categoryId": "center-tables",
    "categoryTitle": "Center Tables",
    "description": "Our Nesting Tables is part of the Center Tables collection. Designed for complete your living space, each piece is built to order using premium materials suited for residential and commercial spaces across Bengaluru.",
    "family": "tables",
    "features": [
      "Handcrafted Nesting Tables built to your exact size and fabric preference.",
      "Suitable for residential homes, offices, hotels, and commercial spaces.",
      "Available for custom orders, quick visits, and doorstep delivery."
    ],
    "id": "center-tables-nesting-tables",
    "images": [
      "https://cdn.sanity.io/images/nzfscoez/production/7ba3b8f08be22894cde5c61159442b78759413a2-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/5a31f4f89b4a3bbfe05e2b28e5dd0997123a10ff-992x1364.jpg",
      "https://cdn.sanity.io/images/nzfscoez/production/dcaf41dccf588f3852c809b8d7449bddc4d5fd9b-992x1403.jpg"
    ],
    "name": "Nesting Tables",
    "slug": "center-tables-nesting-tables",
    "specs": [
      {
        "label": "Category",
        "value": "Center Tables"
      },
      {
        "label": "Brand",
        "value": "Unique Sofa World"
      },
      {
        "label": "Availability",
        "value": "Custom Made to Order"
      },
      {
        "label": "Style",
        "value": "Nesting Tables"
      },
      {
        "label": "Services",
        "value": "Delivery, Setup"
      }
    ],
    "summary": "Premium Nesting Tables by Unique Sofa World — handcrafted for quality and lasting comfort.",
    "tags": [
      "Center Tables",
      "Nesting Tables",
      "Unique Sofa World"
    ],
    "type": "Nesting Tables"
  }
];
